version: build-{build}

clone_depth: 50

environment:
  PERL_CPANM_OPT: "--notest --force --skip-satisfied"

platform:
  - x86
  - x64

install:
  - "cpan App::cpanminus"
  - "cpanm Dist::Zilla"
  - "dzil authordeps | cpanm"
  - "dzil listdeps --author | cpanm"

before_build:
  - "dzil build --in build-dir"

build_script:
  - "dzil listdeps | cpanm"
  - "cd build-dir"
  - "cpanm --installdeps ."
  - "cd .."

test_script:
  - "dzil test --release"
