---
abstract: 'Alien package for the MuPDF PDF rendering library'
author:
  - 'Zakariyya Mughal <zmughal@cpan.org>'
build_requires:
  Cwd: '0'
  File::Basename: '0'
  IPC::Open3: '0'
  Module::Load: '0'
  Symbol: '0'
  Test::More: '0'
configure_requires:
  Alien::Base::ModuleBuild: '0.020'
  File::ShareDir: '1.03'
  Path::Class: '0.013'
dynamic_config: 1
generated_by: 'Dist::Zilla version 6.005, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-MuPDF
recommends:
  Inline: '0.67'
  Inline::C: '0.62'
requires:
  Alien::Base: '0.020'
  File::ShareDir: '1.03'
  File::Spec: '0'
  Path::Class: '0.013'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  homepage: https://github.com/project-renard/p5-Alien-MuPDF
  repository: https://github.com/project-renard/p5-Alien-MuPDF.git
version: 0.005_01
